name: Compare Tags Between Two branches
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source branch'
        required: true
        default: 'main'
        type: choice
        options:
          - main
      target:
        description: 'Target branch'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
jobs:
  compare-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --tags
      - name: Compare tags between source and target
        run: |
          SOURCE_BRANCH="${{ github.event.inputs.source }}"
          TARGET_BRANCH="${{ github.event.inputs.target }}"

          echo "## Tag Comparison Report" >> $GITHUB_STEP_SUMMARY
          echo "Comparing **$SOURCE_BRANCH** (source) vs **$TARGET_BRANCH** (target)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Get tags from source branch
          source_tags=$(git tag --merged origin/$SOURCE_BRANCH | grep -E '^REG-[0-9]+\.' | sort -V)

          # Get tags from target branch
          target_tags=$(git tag --merged origin/$TARGET_BRANCH | grep -E '^REG-[0-9]+\.' | sort -V)

          echo "### Tags in $SOURCE_BRANCH branch:"
          echo "$source_tags"
          echo ""

          echo "### Tags in $TARGET_BRANCH branch:"
          echo "$target_tags"
          echo ""

          # Find tags in source but not in target (missing in target)
          missing_in_target=$(comm -23 <(echo "$source_tags" | sort) <(echo "$target_tags" | sort))

          echo "### Tags missing in $TARGET_BRANCH (present in $SOURCE_BRANCH but not in $TARGET_BRANCH):"
          if [ -n "$missing_in_target" ]; then
            echo "$missing_in_target" | sed 's/\(REG-[0-9]\+\)\..*/\1/' | sort -u
            echo ""
            echo "**Raw tags:**"
            echo "$missing_in_target"
          else
            echo "No tags missing in $TARGET_BRANCH"
          fi
          echo ""

          # Add to GitHub summary
          echo "### Tags missing in $TARGET_BRANCH (REG-xxxx format):" >> $GITHUB_STEP_SUMMARY
          if [ -n "$missing_in_target" ]; then
            echo "$missing_in_target" | sed 's/\(REG-[0-9]\+\)\..*/\1/' | sort -u >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Raw tags:**" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "$missing_in_target" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "No tags missing in $TARGET_BRANCH" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Output results as artifacts
        run: |
          SOURCE_BRANCH="${{ github.event.inputs.source }}"
          TARGET_BRANCH="${{ github.event.inputs.target }}"

          mkdir -p tag-comparison-results

          # Get tags from source branch
          source_tags=$(git tag --merged origin/$SOURCE_BRANCH | grep -E '^REG-[0-9]+\.' | sort -V)

          # Get tags from target branch
          target_tags=$(git tag --merged origin/$TARGET_BRANCH | grep -E '^REG-[0-9]+\.' | sort -V)

          # Find tags missing in target
          missing_in_target=$(comm -23 <(echo "$source_tags" | sort) <(echo "$target_tags" | sort))

          # Create output file
          echo "Tags missing in $TARGET_BRANCH (present in $SOURCE_BRANCH but not in $TARGET_BRANCH):" > tag-comparison-results/missing-in-target.txt
          echo "" >> tag-comparison-results/missing-in-target.txt
          echo "REG-xxxx format:" >> tag-comparison-results/missing-in-target.txt
          if [ -n "$missing_in_target" ]; then
            echo "$missing_in_target" | sed 's/\(REG-[0-9]\+\)\..*/\1/' | sort -u >> tag-comparison-results/missing-in-target.txt
            echo "" >> tag-comparison-results/missing-in-target.txt
            echo "Raw tags:" >> tag-comparison-results/missing-in-target.txt
            echo "$missing_in_target" >> tag-comparison-results/missing-in-target.txt
          else
            echo "No tags missing in $TARGET_BRANCH" >> tag-comparison-results/missing-in-target.txt
          fi
      - name: Upload comparison results
        uses: actions/upload-artifact@v4
        with:
          name: tag-comparison-results
          path: tag-comparison-results/
